package com.dwetherbee.crossrexapp.database;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.dwetherbee.crossrexapp.database.UserDao;
import com.dwetherbee.crossrexapp.database.GoalDao;
import com.dwetherbee.crossrexapp.database.ExerciseDao;
import com.dwetherbee.crossrexapp.database.ExerciseWorkoutDao;
import com.dwetherbee.crossrexapp.database.WorkoutDao;
import com.dwetherbee.crossrexapp.database.UserWorkoutDao;
import com.dwetherbee.crossrexapp.database.ExerciseResultDao;
import com.dwetherbee.crossrexapp.database.WorkoutScheduleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        UserDao.createTable(db, ifNotExists);
        GoalDao.createTable(db, ifNotExists);
        ExerciseDao.createTable(db, ifNotExists);
        ExerciseWorkoutDao.createTable(db, ifNotExists);
        WorkoutDao.createTable(db, ifNotExists);
        UserWorkoutDao.createTable(db, ifNotExists);
        ExerciseResultDao.createTable(db, ifNotExists);
        WorkoutScheduleDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        UserDao.dropTable(db, ifExists);
        GoalDao.dropTable(db, ifExists);
        ExerciseDao.dropTable(db, ifExists);
        ExerciseWorkoutDao.dropTable(db, ifExists);
        WorkoutDao.dropTable(db, ifExists);
        UserWorkoutDao.dropTable(db, ifExists);
        ExerciseResultDao.dropTable(db, ifExists);
        WorkoutScheduleDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(UserDao.class);
        registerDaoClass(GoalDao.class);
        registerDaoClass(ExerciseDao.class);
        registerDaoClass(ExerciseWorkoutDao.class);
        registerDaoClass(WorkoutDao.class);
        registerDaoClass(UserWorkoutDao.class);
        registerDaoClass(ExerciseResultDao.class);
        registerDaoClass(WorkoutScheduleDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
