package com.dwetherbee.crossrexapp.database;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.dwetherbee.crossrexapp.database.WorkoutSchedule;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table WORKOUT_SCHEDULE.
*/
public class WorkoutScheduleDao extends AbstractDao<WorkoutSchedule, Long> {

    public static final String TABLENAME = "WORKOUT_SCHEDULE";

    /**
     * Properties of entity WorkoutSchedule.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Location = new Property(1, String.class, "location", false, "LOCATION");
        public final static Property Date = new Property(2, java.util.Date.class, "date", false, "DATE");
        public final static Property UserId = new Property(3, Long.class, "userId", false, "USER_ID");
        public final static Property WorkoutId = new Property(4, Long.class, "workoutId", false, "WORKOUT_ID");
    };

    private DaoSession daoSession;

    private Query<WorkoutSchedule> user_SchedulesQuery;
    private Query<WorkoutSchedule> workout_SchedulesQuery;

    public WorkoutScheduleDao(DaoConfig config) {
        super(config);
    }
    
    public WorkoutScheduleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'WORKOUT_SCHEDULE' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'LOCATION' TEXT," + // 1: location
                "'DATE' INTEGER," + // 2: date
                "'USER_ID' INTEGER," + // 3: userId
                "'WORKOUT_ID' INTEGER);"); // 4: workoutId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'WORKOUT_SCHEDULE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, WorkoutSchedule entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(2, location);
        }
 
        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(3, date.getTime());
        }
 
        Long userId = entity.getUserId();
        if (userId != null) {
            stmt.bindLong(4, userId);
        }
 
        Long workoutId = entity.getWorkoutId();
        if (workoutId != null) {
            stmt.bindLong(5, workoutId);
        }
    }

    @Override
    protected void attachEntity(WorkoutSchedule entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public WorkoutSchedule readEntity(Cursor cursor, int offset) {
        WorkoutSchedule entity = new WorkoutSchedule( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // location
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // date
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // userId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // workoutId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, WorkoutSchedule entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLocation(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setUserId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setWorkoutId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(WorkoutSchedule entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(WorkoutSchedule entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "schedules" to-many relationship of User. */
    public List<WorkoutSchedule> _queryUser_Schedules(Long userId) {
        synchronized (this) {
            if (user_SchedulesQuery == null) {
                QueryBuilder<WorkoutSchedule> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UserId.eq(null));
                user_SchedulesQuery = queryBuilder.build();
            }
        }
        Query<WorkoutSchedule> query = user_SchedulesQuery.forCurrentThread();
        query.setParameter(0, userId);
        return query.list();
    }

    /** Internal query to resolve the "schedules" to-many relationship of Workout. */
    public List<WorkoutSchedule> _queryWorkout_Schedules(Long workoutId) {
        synchronized (this) {
            if (workout_SchedulesQuery == null) {
                QueryBuilder<WorkoutSchedule> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.WorkoutId.eq(null));
                workout_SchedulesQuery = queryBuilder.build();
            }
        }
        Query<WorkoutSchedule> query = workout_SchedulesQuery.forCurrentThread();
        query.setParameter(0, workoutId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getWorkoutDao().getAllColumns());
            builder.append(" FROM WORKOUT_SCHEDULE T");
            builder.append(" LEFT JOIN USER T0 ON T.'USER_ID'=T0.'_id'");
            builder.append(" LEFT JOIN WORKOUT T1 ON T.'WORKOUT_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected WorkoutSchedule loadCurrentDeep(Cursor cursor, boolean lock) {
        WorkoutSchedule entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User user = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
        entity.setUser(user);
        offset += daoSession.getUserDao().getAllColumns().length;

        Workout workout = loadCurrentOther(daoSession.getWorkoutDao(), cursor, offset);
        entity.setWorkout(workout);

        return entity;    
    }

    public WorkoutSchedule loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<WorkoutSchedule> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<WorkoutSchedule> list = new ArrayList<WorkoutSchedule>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<WorkoutSchedule> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<WorkoutSchedule> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
